comment/Ch3-03to04/0711
pastleo/webgl-book-examples pull request #19
Opened 2022-07-11 14:20 UTC by GeorgiaChiu

其實應該是從第三章的01-04comment修改
心得是好佩服數學家還有寫出程式去計算的人
XD

2022-07-16 12:51 UTC, pastleo requested changes
感謝幫忙 :pray: 
稍微看過覺得有這幾個可以改，不好意思麻煩～

2022-07-16 12:51 UTC, pastleo commented on ch3/01/main.js
> +    state: {  // 初始 tranform 值
`初始 tranform 值` => `初始 tranform 狀態`，然後 `//` 前面一個空白鍵就好

2022-07-16 12:51 UTC, pastleo commented on ch3/01/main.js
> +//  create attribute buffer
```diff
-//  create attribute buffer 
+// create attribute buffer
```

2022-07-16 12:51 UTC, pastleo commented on ch3/01/main.js
> +// 接受四個頂點座標，產生兩個三角形的工具
`產生兩個三角形的工具` => `產生兩個三角形組成一個長方形`

2022-07-16 12:51 UTC, pastleo commented on ch3/04/main.js
> +// 更新 cameraPosition
這個註解寫在 245 行比較好

2022-07-16 12:51 UTC, pastleo commented on ch3/04/main.js
> +  // 使 x, y 以畫面中央為原點
這個註解似乎比較適合放在 306-307 行之間

2022-07-19 07:14 UTC, GeorgiaChiu commented on ch3/01/main.js
> +    state: {  // 初始 tranform 值
ok

2022-07-19 07:15 UTC, GeorgiaChiu commented on ch3/01/main.js
> +// 接受四個頂點座標，產生兩個三角形的工具
ok

2022-07-19 07:17 UTC, GeorgiaChiu commented on ch3/04/main.js
> +// 更新 cameraPosition
阿 那時候寫錯了 已改

2022-07-19 07:18 UTC, GeorgiaChiu commented on ch3/04/main.js
> +  // 使 x, y 以畫面中央為原點
ok

2022-07-19 12:42 UTC, pastleo commented on ch3/01/main.js
> +//  create attribute buffer
後面還有一個多的空白鍵

2022-07-19 12:57 UTC, pastleo commented on ch2/07/main.js
> +  // 平移 state.offset * 旋轉 state.rotation * 縮放 state.scale * 平移 state.translate
看來你把 https://github.com/pastleo/webgl-book-examples/pull/13 的修正寫在這邊了，這邊該修改的修改好我幫你處理吧

2022-07-20 05:12 UTC, GeorgiaChiu commented on ch3/01/main.js
> +//  create attribute buffer
喔喔喔~~~!

2022-07-20 05:14 UTC, GeorgiaChiu commented on ch2/07/main.js
> +  // 平移 state.offset * 旋轉 state.rotation * 縮放 state.scale * 平移 state.translate
喔喔 了解 我改了兩次

2022-07-20 13:43 UTC, pastleo approved these changes

2022-07-20 13:44 UTC, merged